Comments on osx build and markdown linting (M1, arm64, building)
flipperdevices/qFlipper pull request #96
Opened 2022-07-30 15:44 UTC by daconstenla

This change fixes most of the warnings shown by [markdownlint](https://github.com/DavidAnson/vscode-markdownlint) from the `README.md` and `contrib/README.md`.

```sh
markdownlint README.md 2>&1 |wc -l
      66
```
after the adjustments there are `10` warnings all related to line length:

```sh
markdownlint README.md 2>&1 |wc -l             
      10 
```

It also does add one missing dependency when building on OSX (`create-dmg`) and a comment about `qt@6` not being compatible yet, I've seen #69 which might fix this problem.

There is one more change which is "forced" architecture when using docker-compose to prevent trying to build with different than supported architecture `linux/amd64`, otherwise packages will fail to be found and installed.

2023-01-02 11:24 UTC, zhovner requested changes
Most of these changes are useless.

2023-01-02 11:24 UTC, zhovner commented on README.md
> +![qFlipper](https://cdn.flipperzero.one/qflipper_logo_with_connected_flipper.png "connect the flipperzero")
You can't add image width using markdown. This image will be too lage.

2023-01-02 11:24 UTC, zhovner commented on README.md
> +
Why?

2023-01-02 11:24 UTC, zhovner commented on README.md
> +
Why?

2023-01-02 11:24 UTC, zhovner commented on README.md
> +* MS Visual Studio 2019 or newer
Why?

2023-01-13 10:06 UTC, daconstenla commented
Hi @zhovner thanks for the review!

I made those changes based on a `markdownlint` as mentioned in the description, there are `66` identified warnings, fixed those non related to line length.

I guess I could remove those markdown updates and just stick to m1 build.

2023-10-29 01:27 UTC, closed without merging